Members
Projeto-FrontEnd-Fusion/api-xmen pull request #5
Opened 2024-12-30 23:58 UTC by LuisFernandoL

Estou adicionando a pasta members ao projeto.

2025-01-06 20:49 UTC, lucasoliveirabr requested changes
@LuisFernandoL Realizar as mudanças sugeridas para aprovação do Pull Request.

2025-01-06 20:49 UTC, lucasoliveirabr commented on .env.template
Reverter a remoção do `.env.template` para que sirva de guia a quem posteriormente for executar o projeto localmente.

2025-01-06 20:49 UTC, lucasoliveirabr commented on src/api/member/memberRouter.ts
> +});
fix: correct typo

```suggestion
import { createApiResponses } from "@/api-docs/openAPIResponseBuilders";
import { CreateMemberSchema, GetMemberSchema, MemberSchema, UpdateMemberSchema } from "@/api/member/memberModel";
import { validateRequest } from "@/common/utils/httpHandlers";
import { OpenAPIRegistry } from "@asteasolutions/zod-to-openapi";
import express, { type Router } from "express";
import { StatusCodes } from "http-status-codes";
import { z } from "zod";
import { memberController } from "./memberController";

export const memberRegistry = new OpenAPIRegistry();
export const memberRouter: Router = express.Router();

memberRegistry.register("Member", MemberSchema);

memberRouter.post("/", validateRequest(CreateMemberSchema), memberController.createMember);
memberRegistry.registerPath({
  method: "post",
  path: "/members",
  operationId: "createMember",
  description: "Create a member.",
  summary: "Create Member",
  tags: ["Member"],
  request: {
    body: {
      required: true,
      content: {
        "application/json": { schema: CreateMemberSchema.shape.body },
      },
    },
  },
  responses: createApiResponses([
    {
      statusCode: StatusCodes.CREATED,
      description: "Member successfully created.",
      schema: MemberSchema,
    },
    {
      statusCode: StatusCodes.BAD_REQUEST,
      description: "Invalid data supplied.",
    },
    {
      statusCode: StatusCodes.INTERNAL_SERVER_ERROR,
      description: "An error occurred while creating the member.",
    },
  ]),
});

memberRouter.get("/", memberController.getMembers);
memberRegistry.registerPath({
  method: "get",
  path: "/members",
  operationId: "findAllMembers",
  description: "Retieve all members.",
  summary: "Get all members",
  tags: ["Member"],
  responses: createApiResponses([
    {
      statusCode: StatusCodes.OK,
      description: "All members sucessefully found.",
      schema: z.array(MemberSchema),
    },
    {
      statusCode: StatusCodes.NOT_FOUND,
      description: "No members found.",
    },
    {
      statusCode: StatusCodes.INTERNAL_SERVER_ERROR,
      description: "An error occurred while retrieving all members.",
    },
  ]),
});

memberRouter.get("/:id", validateRequest(GetMemberSchema), memberController.getMember);
memberRegistry.registerPath({
  method: "get",
  path: "/members/{id}",
  operationId: "findMemberById",
  description: "Retrieve a member by their ID.",
  summary: "Get Member",
  tags: ["Member"],
  request: { params: GetMemberSchema.shape.params },
  responses: createApiResponses([
    {
      statusCode: StatusCodes.OK,
      description: "Member successfully found.",
      schema: MemberSchema,
    },
    {
      statusCode: StatusCodes.BAD_REQUEST,
      description: "Invalid data supplied.",
    },
    {
      statusCode: StatusCodes.NOT_FOUND,
      description: "Member not found.",
    },
    {
      statusCode: StatusCodes.INTERNAL_SERVER_ERROR,
      description: "An error occurred while finding the member.",
    },
  ]),
});

memberRouter.put("/:id", validateRequest(UpdateMemberSchema), memberController.updateMember);
memberRegistry.registerPath({
  method: "put",
  path: "/members/{id}",
  operationId: "updateMember",
  description: "Update a member by their ID.",
  summary: "Update Member",
  tags: ["Member"],
  request: {
    params: UpdateMemberSchema.shape.params,
    body: {
      required: true,
      content: {
        "application/json": { schema: UpdateMemberSchema.shape.body },
      },
    },
  },
  responses: createApiResponses([
    {
      statusCode: StatusCodes.OK,
      description: "Member sucessfully updated.",
      schema: z.null(),
    },
    {
      statusCode: StatusCodes.BAD_REQUEST,
      description: "Invalid data supplied.",
    },
    {
      statusCode: StatusCodes.NOT_FOUND,
      description: "Member not found.",
    },
    {
      statusCode: StatusCodes.INTERNAL_SERVER_ERROR,
      description: "An error occurred while updating the member.",
    },
  ]),
});

memberRouter.delete("/:id", validateRequest(GetMemberSchema), memberController.deleteMember);
memberRegistry.registerPath({
  method: "delete",
  path: "/members/{id}",
  operationId: "deleteMember",
  description: "Delete a member by their ID.",
  summary: "Delete Member",
  tags: ["Member"],
  request: { params: GetMemberSchema.shape.params },
  responses: createApiResponses([
    {
      statusCode: StatusCodes.OK,
      description: "Member sucessfully deleted.",
      schema: z.null(),
    },
    {
      statusCode: StatusCodes.BAD_REQUEST,
      description: "Invalid data supplied.",
    },
    {
      statusCode: StatusCodes.NOT_FOUND,
      description: "Member not found.",
    },
    {
      statusCode: StatusCodes.INTERNAL_SERVER_ERROR,
      description: "An error ocurred while deleting the member.",
    },
  ]),
});
```

2025-01-06 20:49 UTC, lucasoliveirabr commented on src/api/member/memberService.ts
> +export const memberService = new MemberService();
fix: correct typo

```suggestion
import { StatusCodes } from "http-status-codes";

import {
  type CreateMemberDto,
  CreateMemberDtoSchema,
  type Member,
  type UpdateMemberDto,
  UpdateMemberDtoSchema,
} from "@/api/member/memberModel";
import { MemberRepository } from "@/api/member/memberRepository";
import { ServiceResponse } from "@/common/models/serviceResponse";
import { logger } from "@/server";

export class MemberService {
  private memberRepository: MemberRepository;

  constructor(repository: MemberRepository = new MemberRepository()) {
    this.memberRepository = repository;
  }

  async create(memberToBeCreate: CreateMemberDto): Promise<ServiceResponse<Member | null>> {
    try {
      const validationResult = CreateMemberDtoSchema.safeParse(memberToBeCreate);
      if (!validationResult.success) {
        const errorMessages = validationResult.error.errors
          .map((error) => `${error.path.join(".")}: ${error.message}`)
          .join(";");
        logger.error(`Invalid data supplied: ${errorMessages}.`);
        return ServiceResponse.failure(`Invalid data supplied: ${errorMessages}.`, null, StatusCodes.BAD_REQUEST);
      }
      const member: Member = await this.memberRepository.createAsync(memberToBeCreate);
      return ServiceResponse.success<Member>("Member successfully created.", member, StatusCodes.CREATED);
    } catch (ex) {
      const errorMessage = `Error while creating a member ${memberToBeCreate}:, ${(ex as Error).message}`;
      logger.error(errorMessage);
      return ServiceResponse.failure(
        "An error occurred while creating the member.",
        null,
        StatusCodes.INTERNAL_SERVER_ERROR,
      );
    }
  }

  async findAll(): Promise<ServiceResponse<Member[] | null>> {
    try {
      const members = await this.memberRepository.findAllAsync();
      if (!members || members.length === 0) {
        return ServiceResponse.failure("No members found.", null, StatusCodes.NOT_FOUND);
      }
      return ServiceResponse.success<Member[]>("All Members successfully found.", members, StatusCodes.OK);
    } catch (ex) {
      const errorMessage = `Error while finding all members: $${(ex as Error).message}`;
      logger.error(errorMessage);
      return ServiceResponse.failure(
        "An error occurred while retrieving all members.",
        null,
        StatusCodes.INTERNAL_SERVER_ERROR,
      );
    }
  }

  async findById(id: number): Promise<ServiceResponse<Member | null>> {
    try {
      if (Number.isNaN(id)) {
        return ServiceResponse.failure(
          " Invalid data supplied: id: ID must be a numeric value, id: ID must a be a positive number.",
          null,
          StatusCodes.BAD_REQUEST,
        );
      }
      const member = await this.memberRepository.findByIdAsync(id);
      if (!member) {
        return ServiceResponse.failure("Member not found.", null, StatusCodes.NOT_FOUND);
      }
      return ServiceResponse.success<Member>("Member successfully found.", member, StatusCodes.OK);
    } catch (ex) {
      const errorMessage = `Error while finding the member with id ${id}:, ${(ex as Error).message}`;
      logger.error(errorMessage);
      return ServiceResponse.failure(
        "An error occurred while finding the member.",
        null,
        StatusCodes.INTERNAL_SERVER_ERROR,
      );
    }
  }

  async update(id: number, newMemberData: UpdateMemberDto): Promise<ServiceResponse<Member | null>> {
    try {
      if (Number.isNaN(id)) {
        return ServiceResponse.failure(
          "Invalid data supplied: id: ID must be a numeric value, id: ID must be a positive number.",
          null,
          StatusCodes.BAD_REQUEST,
        );
      }

      const validationResult = UpdateMemberDtoSchema.safeParse(newMemberData);
      if (!validationResult.success) {
        const errorMessages = validationResult.error.errors
          .map((error) => `${error.path.join(".")}: ${error.message}`)
          .join("; ");
        logger.error(`Invalid data supplied: ${errorMessages}.`);
        return ServiceResponse.failure(`Invalid data supplied: ${errorMessages}.`, null, StatusCodes.BAD_REQUEST);
      }

      const member = await this.memberRepository.findByIdAsync(id);
      if (!member) {
        return ServiceResponse.failure("Member not found.", null, StatusCodes.NOT_FOUND);
      }

      await this.memberRepository.updateAsync(id, newMemberData);

      const updateMember = await this.memberRepository.findByIdAsync(id);
      if (!updateMember) {
        return ServiceResponse.failure(
          "Failed to retrieve the updated member.",
          null,
          StatusCodes.INTERNAL_SERVER_ERROR,
        );
      }

      return ServiceResponse.success("Member successfully updated.", updateMember, StatusCodes.OK);
    } catch (ex) {
      const errorMessage = `Error while updating the member whith id ${id} and their new data ${newMemberData};,${
        (ex as Error).message
      }`;
      logger.error(errorMessage);
      return ServiceResponse.failure(
        "An error occurred while updating the member.",
        null,
        StatusCodes.INTERNAL_SERVER_ERROR,
      );
    }
  }

  async delete(id: number): Promise<ServiceResponse<Member | null>> {
    try {
      if (Number.isNaN(id)) {
        return ServiceResponse.failure(
          "Invalid data suppplied: id: ID must be a numeric value, id: ID must a be a positive number.",
          null,
          StatusCodes.BAD_REQUEST,
        );
      }

      const member = await this.memberRepository.findByIdAsync(id);
      if (!member) {
        return ServiceResponse.failure("Member not found.", null, StatusCodes.NOT_FOUND);
      }

      await this.memberRepository.deleteAsync(id);
      return ServiceResponse.success("Member successfully deleted.", null, StatusCodes.OK);
    } catch (ex) {
      const errorMessage = `Error while deletinh the member with id ${id}:, ${(ex as Error).message}`;
      logger.error(errorMessage);
      return ServiceResponse.failure(
        "An error ocurred while deleting the member.",
        null,
        StatusCodes.INTERNAL_SERVER_ERROR,
      );
    }
  }
}

export const memberService = new MemberService();
```

2025-01-09 23:42 UTC, LuisFernandoL commented
Adicionei a pasta de "projects" ao projeto, juntamento com .env.template

2025-01-13 22:07 UTC, lucasoliveirabr approved these changes

2025-01-13 22:07 UTC, merged